# Generated by Django 4.0.3 on 2023-07-19 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hats_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hats',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hat', to='hats_rest.locationvo'),
        ),
        migrations.AlterField(
            model_name='locationvo',
            name='import_href',
            field=models.URLField(unique=True),
        ),
    ]
