# Generated by Django 4.0.3 on 2023-07-19 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0002_binvo_bin_number_binvo_bin_size_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoe',
            old_name='bin',
            new_name='bin_number',
        ),
    ]
