# Generated by Django 4.0.3 on 2023-07-19 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0003_rename_bin_shoe_bin_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoe',
            old_name='bin_number',
            new_name='bin',
        ),
    ]
